name: Create release and tags from PR
on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: The pull request to release
        type: string
        required: true
  
jobs:
  refresh-app-token:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: set secret
        run: |
          gh secret set MYSECRET --body "${{ steps.app-token.outputs.token }}"
  release-pull-request:
    name: Release pull request
    permissions:
      pull-requests: write
      contents: read
    uses: nilsgstrabo/learnrelease/.github/workflows/template-create-release-from-pr.yml@main
    with:
      pull-request-number: ${{ inputs.pr-number }}
      github-app-id: ${{ vars.GH_APP_ID }}
      use-github-app-token: true
    secrets:
      github-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
  print-result:
    runs-on: ubuntu-latest
    name: Print outcome of release
    needs: release-pull-request
    steps:
      - name: Print result
        run: |
          echo "release-result: ${{ needs.release-pull-request.outputs.release-result }}"
          echo "version: ${{ needs.release-pull-request.outputs.version }}"
          echo "tag: ${{ needs.release-pull-request.outputs.tag }}"
          echo "commit: ${{ needs.release-pull-request.outputs.commit }}"
          echo "is-prerelease: ${{ needs.release-pull-request.outputs.is-prerelease }}"
    