name: Create release and tags
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  unreleased-prs-metadata:
    name: Get list of pending release pull requests
    permissions:
      pull-requests: read
    uses: nilsgstrabo/learnrelease/.github/workflows/template-unreleased-pr-metadata.yml@main
  release-pull-request:
    name: Release pull request
    needs: 
      - unreleased-prs-metadata
    if: needs.unreleased-prs-metadata.outputs.unreleased-pull-request-count > 0
    strategy:
      matrix:
        pull-request-number: ${{ fromJson(needs.unreleased-prs-metadata.outputs.unreleased-pull-requests) }}
    permissions:
      pull-requests: write
      contents: read
      issues: write
    uses: nilsgstrabo/learnrelease/.github/workflows/template-create-release-from-pr.yml@main
    with:
      pull-request-number: ${{ matrix.pull-request-number }}
      github-app-id: ${{ vars.GH_APP_ID }}
      use-github-app-token: true
    secrets:
      github-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
  print-result:
    name: Print results of last release job
    runs-on: ubuntu-latest
    needs: release-pull-request
    steps:
      - name: Print result
        run: |
          echo "release-result: ${{ needs.release-pull-request.outputs.release-result }}"
          echo "version: ${{ needs.release-pull-request.outputs.version }}"
          echo "tag: ${{ needs.release-pull-request.outputs.tag }}"
          echo "commit: ${{ needs.release-pull-request.outputs.commit }}"
          echo "is-prerelease: ${{ needs.release-pull-request.outputs.is-prerelease }}"
    