name: Create release and tags
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  unreleased-prs-metadata:
    permissions:
      pull-requests: read
    uses: nilsgstrabo/learnrelease/.github/workflows/template-unreleased-prs-metadata.yml@main
  release-token:
    needs: unreleased-prs-metadata
    if: needs.unreleased-prs-metadata.outputs.unreleased_pull_request_count > 0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
  release-pull-request:
    needs: 
      - unreleased-prs-metadata
      - release-token
    if: needs.unreleased-prs-metadata.outputs.unreleased_pull_request_count > 0
    strategy:
      matrix:
        pull-request-number: ${{ fromJson(needs.unreleased-prs-metadata.outputs.unreleased_pull_requests) }}
    permissions:
      pull-requests: write
      contents: read
    uses: nilsgstrabo/learnrelease/.github/workflows/template-release-pr.yml@main
    with:
      pull-request-number: ${{ matrix.pull-request-number }}
    secrets:
      gh-release-token: ${{ secrets.RELEASE_GH_TOKEN }}
    