name: Prepare release PR

on:
    push: 
        tags:
            - v*
        branches: 
            - main
    workflow_dispatch:



jobs:
    prepare-release:
        name: Prepare release
        runs-on: ubuntu-latest
        permissions: 
            pull-requests: write
            contents: read
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod
            - name: Install git-semver
              run: |
                go install github.com/psanetra/git-semver/cli@v1.1.2
                # mv $(which cli) $(dirname $(which cli))/git-semver
            - name: Build release and prerelease tag
              id: ver
              run: |
                next_prerelease_tag=v$(cli next --pre-release-tag rc --pre-release-counter)
                next_stable_tag=v$(cli next)
                latest_tag=v$(cli latest --include-pre-releases)

                if git show-ref --quiet --verify "refs/tags/${latest_tag}"; then
                    echo "Counting commits since ${latest_tag}"
                    commits_since_latest_tag=$(git log ${latest_tag}..HEAD | wc -l)
                else
                    echo "Counting all commits"
                    commits_since_latest_tag=$(git log | wc -l)
                fi

                echo "next_prerelease_tag=$next_prerelease_tag" >>"$GITHUB_OUTPUT"
                echo "next_stable_tag=$next_stable_tag" >>"$GITHUB_OUTPUT"
                echo "latest_tag=$latest_tag" >>"$GITHUB_OUTPUT"
                echo "commits_since_latest_tag=$commits_since_latest_tag" >>"$GITHUB_OUTPUT"
            - name: Show computed version
              run: |
                echo "next_prerelease_tag = ${{ steps.ver.outputs.next_prerelease_tag }}"
                echo "next_stable_tag = ${{ steps.ver.outputs.next_stable_tag }}"
                echo "latest_tag = ${{ steps.ver.outputs.latest_tag }}"
                echo "commits_since_latest_tag = ${{ steps.ver.outputs.commits_since_latest_tag }}"
                yq -V

                
            - name: Create release PR
              id: release-pr
              uses: peter-evans/create-pull-request@v7
              with:
                delete-branch: true
                title: Release ${{ steps.ver.outputs.next_stable_tag }}
                branch: release/stable
                labels: stablerelease

            

