on:
    push:
      branches:
        - main
  
permissions:
    contents: write
    pull-requests: write
  
name: Prerelease
  
jobs:
    release-please:
      runs-on: ubuntu-latest
      steps:
        - uses: googleapis/release-please-action@v4
          with:
            token: ${{ secrets.GH_TOKEN }}
            config-file: .release-please/prerelease-config.json
            manifest-file: .release-please/prerelease-manifest.json


