name: Create tag and releases for unrelease pull requests
on:
  workflow_dispatch:
  
jobs:
  unreleased-metadata:
    permissions:
      pull-requests: write
      contents: read
    uses: nilsgstrabo/learnrelease/.github/workflows/template-unreleased-prs-metadata.yml@main
  release-pull-request:
    needs: unreleased-metadata
    strategy:
      matrix:
        pull-request-number: ${{ fromJson(needs.unreleased-metadata.outputs.unreleased_pull_requests) }}
    permissions:
      pull-requests: write
      contents: read
    uses: nilsgstrabo/learnrelease/.github/workflows/template-release-pr.yml@main
    with:
      pull-request-number: ${{ matrix.pull-request-number }}
    secrets:
      gh-release-token: ${{ secrets.RELEASE_GH_TOKEN }}          
  
  
      

    