name: Release
on:
  push:
    branches:
      - main

jobs:
  metadata:
    name: Metadata
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: read
      contents: read
    outputs:
      pending_releases: ${{ steps.metadata.outputs.pending_releases }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Metadata
        id: metadata
        env:
          GH_TOKEN: ${{ github.token }}  
        run: |
          pending_releases=$(gh pr list --json title,labels,mergeCommit,state,id --state merged --label "release: pending")
          echo "pending_releases=$pending_releases" >>"$GITHUB_OUTPUT"
      - name: Print metadata
        run: |
          echo ${{ steps.metadata.outputs.pending_releases }}

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - metadata
    strategy:
      matrix:
        release-pr: ${{ fromJson(needs.metadata.outputs.pending_releases) }}
    steps:
      - name: Print
        run: |
          echo "matrix value: ${{ matrix.release-pr }}"
