name: Release
on:
  workflow_dispatch:
    inputs:
      pull-request-number:
        description: Pull request to release
        type: string
        required: true

jobs:
  release:
    permissions:
      pull-requests: write
      contents: read
    uses: nilsgstrabo/learnrelease/.github/workflows/template-release-pr.yml@main
    with:
      pull-request-number: ${{ inputs.pull-request-number }}
    secrets:
      gh-release-token: ${{ secrets.RELEASE_GH_TOKEN }}
      
  result:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Print release output
        run: |
          echo "version: ${{ needs.release.outputs.version }}"
          echo "tag: ${{ needs.release.outputs.tag }}"
          echo "is-prerelease: ${{ needs.release.outputs.is-prerelease }}"
          echo "commit: ${{ needs.release.outputs.commit }}"
    