name: Release
on:
  push:
    branches:
      - main

jobs:
  metadata:
    name: Metadata
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: metadata
        env:
          GH_TOKEN: ${{ github.token }}  
        run: |
          gh pr list --json title,labels,mergeCommit,state --state merged
