name: Release
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}

jobs:
  releases-metadata:
    name: Metadata for pending releases
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: read
      contents: read
    outputs:
      pending_releases: ${{ steps.metadata.outputs.pending_releases }}
      pending_releases_count: ${{ steps.metadata.outputs.pending_releases_count }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Metadata
        id: metadata
        env:
          GH_TOKEN: ${{ github.token }}  
        run: |
          pending_releases=$(gh pr list --json title,number --state merged --label "release: pending")
          pending_releases_count=$(echo $pending_releases | jq '. | length')
          
          echo "pending_releases=$pending_releases" >>"$GITHUB_OUTPUT"
          echo "pending_releases_count=$pending_releases_count" >>"$GITHUB_OUTPUT"

  release:
    name: Create release
    runs-on: ubuntu-latest
    if: ${{ needs.releases-metadata.outputs.pending_releases_count > 0}}
    needs:
      - releases-metadata
    strategy:
      # max-parallel: 1
      matrix:
        release-pr: ${{ fromJson(needs.releases-metadata.outputs.pending_releases) }}
    steps:
      - name: Print
        run: |
          echo "matrix value: ${{ toJson(matrix.release-pr) }}"
