name: Template - Prepare release pull requests
on:
  workflow_call:
    inputs:
      version-file-path:
        description: The path to the file where the new version is written to.
        required: false
        type: string
        default: version.txt
      pre-release-version-prefix:
        description: The prefix to use in identifier for calculating pre-release versions. For example, if this value is set to "rc" (default), the first pre-release version for version "1.5.0" will be "1.5.0-rc.1", then "1.5.0-rc.2", and so on.
        required: true
        type: string
        default: rc
      branch:
        description: The name of the branch to analyze commits for calculating next version. This is also used as the base branch when creating release pull requests. 
        required: true
        type: string
        default: main
      pre-release-pr-branch:
        description: The pull request branch name for pre-releases
        required: true
        type: string
        default: release/pre-release
      stable-release-pr-branch:
        description: The pull request branch name for stable releases
        required: true
        type: string
        default: release/stable-release
      changelog-path:
        description: The path to the changelog to update for stable release pull requests
        required: true
        type: string
        default: CHANGELOG.md
      helm-chart-path:
        description: The path to the Chart.yaml to update for stable- and pre-release pull requests
        required: true
        type: string
      cliff-config-path:
        description: The path to cliff.toml configuration file, used to configure the layout of the changelog. See https://git-cliff.org/docs/configuration/ for more information.
        type: string
      extra-files:
        description: A list of files to update with new version number. For each file, the workflow will look for lines containing the text '# x-patch-semver', and replace anything that matches a semver version with the new version.
        type: string
        required: false

jobs:
    metadata:
      name: Metadata
      runs-on: ubuntu-latest
      permissions:
        contents: read
      outputs:
        next_stable_version: ${{ steps.ver.outputs.next_stable_version }}
        next_prerelease_version: ${{ steps.ver.outputs.next_prerelease_version }}
        next_stable_version_greater_than_latest: ${{ steps.ver.outputs.next_stable_version_greater_than_latest }}
        next_prerelease_version_greater_than_latest: ${{ steps.ver.outputs.next_prerelease_version_greater_than_latest }}
        latest_version: ${{ steps.ver.outputs.latest_version }}
        commits_since_latest_version: ${{ steps.ver.outputs.commits_since_latest_version }}
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: actions/setup-go@v5
          with:
              go-version-file: go.mod
        - name: Install git-semver
          run: |
            go install github.com/psanetra/git-semver/cli@v1.1.2
            mv $(which cli) $(dirname $(which cli))/git-semver
        - name: Build release and prerelease tag
          id: ver
          run: |
            next_prerelease_version=$(git-semver next --pre-release-tag ${{ inputs.pre-release-version-prefix }} --pre-release-counter)
            next_stable_version=$(git-semver next)
            latest_version=$(git-semver latest --include-pre-releases)
            echo "latest_version: $latest_version"
            
            if git show-ref --quiet --verify refs/tags/$v{latest_version}; then
                echo "Counting commits since v${latest_version}"
                commits_since_latest_version=$(git log  --oneline v${latest_version}..HEAD | wc -l)
            else
                echo "Counting all commits"
                commits_since_latest_version=$(git log --oneline | wc -l)
            fi

            next_stable_version_greater_than_latest="false"
            if [ "$(git-semver compare $next_stable_version $latest_version 2>&1)" = ">" ]; then
                next_stable_version_greater_than_latest="true"
            fi

            next_prerelease_version_greater_than_latest="false"
            if [ "$(git-semver compare $next_prerelease_version $latest_version 2>&1)" = ">" ]; then
                next_prerelease_version_greater_than_latest="true"
            fi

            echo "next_prerelease_version=$next_prerelease_version" >>"$GITHUB_OUTPUT"
            echo "next_stable_version=$next_stable_version" >>"$GITHUB_OUTPUT"
            echo "next_stable_version_greater_than_latest=$next_stable_version_greater_than_latest" >>"$GITHUB_OUTPUT"
            echo "next_prerelease_version_greater_than_latest=$next_prerelease_version_greater_than_latest" >>"$GITHUB_OUTPUT"
            echo "commits_since_latest_version=$commits_since_latest_version" >>"$GITHUB_OUTPUT"
        - name: Show computed version
          run: |
            echo "next_prerelease_version = ${{ steps.ver.outputs.next_prerelease_version }}"
            echo "next_stable_version = ${{ steps.ver.outputs.next_stable_version }}"
            echo "next_stable_version_greater_than_latest = ${{ steps.ver.outputs.next_stable_version_greater_than_latest }}"
            echo "next_prerelease_version_greater_than_latest = ${{ steps.ver.outputs.next_prerelease_version_greater_than_latest }}"
            echo "commits_since_latest_version = ${{ steps.ver.outputs.commits_since_latest_version }}"        

    stable-release-pr:
      name: Stable release PR
      runs-on: ubuntu-latest
      needs: metadata
      permissions: 
        pull-requests: write
        contents: write
        issues: write
      steps:
        - name: test extra-files
          run: |
            extrafiles="${{ inputs.extra-files }}"
            echo $extrafiles
            echo "processing files"
            for line in $extrafiles; do
              echo "extra file: $line"
            done
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            ref: ${{ inputs.branch }}
        - name: Generate stable release changelog
          if: needs.metadata.outputs.next_stable_version_greater_than_latest == 'true'
          uses: orhun/git-cliff-action@v4
          with:
            config: ${{ inputs.cliff-config-path }}
            args:
              -vv --tag v${{ needs.metadata.outputs.next_stable_version }} --ignore-tags ${{ inputs.pre-release-version-prefix }}
          env:
            OUTPUT: ${{ inputs.changelog-path }}

        - name: Generate stable release changelog for PR body
          if: needs.metadata.outputs.next_stable_version_greater_than_latest == 'true'  
          id: stable-changelog
          uses: orhun/git-cliff-action@v4
          with:
            config: ${{ inputs.cliff-config-path }}
            args:
              -vv -u --strip all --tag v${{ needs.metadata.outputs.next_stable_version }} --ignore-tags ${{ inputs.pre-release-version-prefix }}
          env:
            OUTPUT: ${{ runner.temp }}/stablechangelog.md

        - name: Update version tracking file
          if: needs.metadata.outputs.next_stable_version_greater_than_latest == 'true'
          run: |
            echo "${{ needs.metadata.outputs.next_stable_version }}" > ${{ inputs.version-file-path }}
        - name: Update extra files
          if: inputs.extra-files != '' && needs.metadata.outputs.next_stable_version_greater_than_latest == 'true'
          working-directory: ./scripts
          run: |
            ./patch-semver.sh "$${{ needs.metadata.outputs.next_stable_version }}" "${{ inputs.extra-files }}"

        # - name: Update stable version in Chart.yaml
        #   if: needs.metadata.outputs.next_stable_version_greater_than_latest == 'true'
        #   env:
        #     version: ${{ needs.metadata.outputs.next_stable_version }}
        #   run: >
        #     yq
        #     '.version = strenv(version), .appVersion = strenv(version)'
        #     -i ${{ inputs.helm-chart-path }}
            
        - name: Create stable release PR
          uses: peter-evans/create-pull-request@v7
          with:
            base: ${{ inputs.branch }}
            delete-branch: true
            title: "chore: release ${{ needs.metadata.outputs.next_stable_version }}"
            branch: ${{ inputs.stable-release-pr-branch }}
            labels: "release: pending"
            body: ${{ steps.stable-changelog.outputs.content }}
            commit-message: "chore(release): prepare for stable release ${{ needs.metadata.outputs.next_stable_version }}"
            sign-commits: true
            add-paths: |
              ${{ inputs.changelog-path }}
              ${{ inputs.helm-chart-path }}

    prerelease-pr:
      name: Prerelease PR
      runs-on: ubuntu-latest
      needs: metadata
      permissions: 
        pull-requests: write
        contents: write
        issues: write
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            ref: ${{ inputs.branch }}
        - name: Generate prerelease changelog for PR body
          if: needs.metadata.outputs.next_prerelease_version_greater_than_latest == 'true' && needs.metadata.outputs.commits_since_latest_version > 0
          id: unreleased-changelog
          uses: orhun/git-cliff-action@v4
          with:
            config: ${{ inputs.cliff-config-path }}
            args:
              -vv -u --strip all --tag v${{ needs.metadata.outputs.next_prerelease_version }}
          env:
            OUTPUT: ${{ runner.temp }}/prereleasechangelog.md
        - name: Update version tracking file
          if: needs.metadata.outputs.next_prerelease_version_greater_than_latest == 'true' && needs.metadata.outputs.commits_since_latest_version > 0
          run: |
            echo "${{ needs.metadata.outputs.next_prerelease_version }}" > ${{ inputs.version-file-path }}
        - name: Update extra files
          if: inputs.extra-files != '' && needs.metadata.outputs.next_stable_version_greater_than_latest == 'true' && needs.metadata.outputs.commits_since_latest_version > 0
          working-directory: ./scripts
          run: |
            ./patch-semver.sh "$${{ needs.metadata.outputs.next_prerelease_version }}" "${{ inputs.extra-files }}"            
        # - name: Update prerelease version in Chart.yaml
        #   if: needs.metadata.outputs.next_prerelease_version_greater_than_latest == 'true' && needs.metadata.outputs.commits_since_latest_version > 0
        #   env:
        #     version: ${{ needs.metadata.outputs.next_prerelease_version }}
        #   run: >
        #     yq
        #     '.version = strenv(version), .appVersion = strenv(version)'
        #     -i ${{ inputs.helm-chart-path }}
        - name: Create prerelease PR
          uses: peter-evans/create-pull-request@v7
          with:
            base: ${{ inputs.branch }}
            delete-branch: true
            title: "chore: prerelease ${{ needs.metadata.outputs.next_prerelease_version }}"
            branch: ${{ inputs.pre-release-pr-branch }}
            labels: "release: pending"
            body: ${{ steps.unreleased-changelog.outputs.content }}
            commit-message: "chore(release): prepare for prerelease ${{ needs.metadata.outputs.next_prerelease_version }}"
            sign-commits: true
            add-paths: |
              ${{ inputs.helm-chart-path }}
