name: Test workflow
on:
    push: 
        tags:
            - '**'
        branches: 
            - main
    workflow_dispatch:
      inputs:
        tag:
          description: The tag to create deployment for
          type: string
          required: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: resolve tag
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref_type }}
          echo ${{ github.ref_name }}
    
    
      
