on:
  workflow_dispatch: 
        
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: 
      contents: read
    steps:
      - name: Create app token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{secrets.GH_APP_PRIVATE_KEY }}
          permission-packages: read
      - uses: docker/login-action@v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ steps.app-token.outputs.token }}
      - name: pull
        run: |
            docker pull ghcr.io/nilsgstrabo/learnrelease:2.5.0-rc.9